openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  # cf. https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml
  $include.petstore: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml#/paths
  # cf. https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/uspto.yaml
  $include.uspto: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/uspto.yaml#/paths
